{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "medusa.fullname" . }}-storefront
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    nginx.ingress.kubernetes.io/ssl-redirect: {{ .Values.ingress.sslRedirect | quote }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.issuer }}
    acme.cert-manager.io/http01-edit-in-place: "true"
  labels:
    {{- include "medusa.labels" . | nindent 4 }}
    app.kubernetes.io/component: storefront
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
        - {{ .Values.ingress.storefront.host }}
      secretName: {{ include "medusa.fullname" . }}-storefront-tls
  rules:
    - host: {{ .Values.ingress.storefront.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "medusa.fullname" . }}-storefront
                port:
                  number: {{ .Values.storefront.port }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "medusa.fullname" . }}-backend
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    nginx.ingress.kubernetes.io/ssl-redirect: {{ .Values.ingress.sslRedirect | quote }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.issuer }}
    acme.cert-manager.io/http01-edit-in-place: "true"
  labels:
    {{- include "medusa.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
        - {{ .Values.ingress.backend.host }}
      secretName: {{ include "medusa.fullname" . }}-backend-tls
  rules:
    - host: {{ .Values.ingress.backend.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "medusa.fullname" . }}-backend
                port:
                  number: {{ .Values.backend.port }}
{{- end }}
